# Generated by Django 3.0.8 on 2021-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('clinic_address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
